### PR TITLE
Update udhr

### PR DESCRIPTION
**Pull request by koheiw**
I noticed that language coverage is poor in the previous dataset, missing important languages like Hebrew. This PR is to change to a more updated dataset from the [UDHR in Unicode Project](https://unicode.org/udhr/).

### CODE REVIEW

**Review by kbenoit — CHANGES_REQUESTED** [review]
Even better!

Questions:
- should we include the previous object as a separate corpus, just in case someone wants to compare?
- what should we use as a docname? Maybe "UDHR-<ISO-639>-<additional code>" ?

Requests:
- Please update the metadata similar to the scheme in the previous udhr object, and used by the other objects. This includes: `[1] "description" "source"      "url"         "author"      "keywords"   
[6] "title"`
- Why not use all of the columns from the table at https://unicode.org/udhr/translations.html, except "Region" (which is empty), and "Deliverables"?

**Comment by koheiw** [comment]
The texts that I used for previous dataset were not properly encoded in UTF-8, so better not use.

I am taking docvars from the individual XML. If you want others too, I can include them but don't want to include all the meta information because I cannot document them in the manual accurately.
```
<udhr iso639-3="ese" xml:lang="ese" key="ese" n="Ese Ejja"  dir='ltr' iso15924='Latn' xmlns="http://www.unhchr.ch/udhr">
```

**Comment by koheiw** [comment]
I don't have strong opinion on the docnames. It should be easy for user to find the docnames for their languages. I always need to look at Note to find docnames. (e.g. German texts are `deu_1901` and `deu_1996`).

**Comment by kbenoit** [comment]
Yeah same here on the docnames, I don't have a strong opinion either. But it makes sense to correspond to the original data naming scheme where possible.

**Comment by kbenoit** [comment]
Sorry Kohei it looks like we were making simultaneous edits after my PR comments…  I fixed a few of those items and updated the construction script. Will leave it to you now - hope I didn’t cause unnecessary work.

**Comment by koheiw** [comment]
Please make changes. I am done today on this branch.

**Comment by koheiw** [comment]
The most difficult part was making the preamble a single paragraph. The last a few commits are all about it.

**Comment by kbenoit** [comment]
OK I updated the construction script, now makes all of the changes except:
- using additional docvars. I would suggest we add BCP47, 15924, OHCHR, and Stage.
- changing the docname. It uses the "Key" variable now but that's not very informative.

**Comment by koheiw** [comment]
@kbenoit I am happy with how it is now. Please merge if you are too.

**Comment by koheiw** [comment]
I don't know if it is printed properly but love it.
```
> corpus_subset(data_corpus_udhr, Direction == "rtl")
Corpus consisting of 15 documents and 4 docvars.
aii :
"ܥܘܬܕܐ ܡܢ ܣܒܒ ܡܘܕܝܬܐ ܒܐܝܩܪܐ ܫܪܫܢܝܐ ܠܟܠܗ ܗܕܡܐ ܕܟܠܦܬ ܕܒܪܢܫܘܬܐ ܘ..."

arb :
"الديباجة لمّا كان الاعتراف بالكرامة المتأصلة في جميع أعضاء ا..."

div :
"ދީބާޖާ ދެންފަހެ، މިނިވަންކަމާއި، ޢަދުލުވެރިކަމާއި، ޞުލްޙަވެރ..."

fuf_adlm :
"𞤐𞤀𞥄𞤚𞤋𞤈𞤑𞤀 𞤚𞤵𞥅𞤺𞤢𞥄𞤣𞤫 𞤱𞤮𞤲𞤣𞤫 𞤸𞤫𞤬𞤼𞤭𞤲𞤺𞤮𞤤 𞤸𞤮𞤪𞤥𞤢 𞤳𞤢𞤤𞤢 𞤲𞤫𞤯𞥆𞤮 𞤫 𞤲'𞤣𞤫𞤪 𞤩..."

heb :
"הכרזה לכל באי עולם בדבר זכויות האדם הואיל והכרה בכבוד הטבעי ..."

mly_arab :
"مقدمه بهاواساڽ ڤڠيعترافن كأوتوهن كموليأن دان حق سامرات سرتا ..."

[ reached max_ndoc ... 9 more documents ]
```

**Pull request merged**
